name: Publish Package

on:
  push:
    branches:
      - main 
  pull_request: 
    branches:
      - "**" 
  workflow_dispatch:

jobs:
  publish:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com

      - name: Install pnpm 
        run: npm install -g pnpm

      - name: Publish to GitHub Packages
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

